### ISSUE TITLE
State in option text is not working

### ISSUE THREAD

**Issue by itsDrac** [real-ezTheDev/GodotEzDialoguePlugin#1]
Godot version 4.0 stable

I am trying to add state variable in one of the option's text, but it seems that EzDialogue is taking that up as `responce.text`

prompt
![image](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/25584851/1f47bcd6-76b7-4a05-8b5c-95daa77717c2)

output
![image](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/25584851/5227e0a9-f343-4976-8bd0-7861a99ccebc)

Expectation: states can be used in option text.

**Comment by itsDrac** [comment]
I think we can use `.format` of String
It also uses dictionary

and is some key isn't found in response text it can ignore that key.

**Comment by real-ezTheDev** [comment]
Injecting variable as part of the choice text has not been considered during the development.
Thank you for pointing out this use case out.

there maybe need to correct the parsing logic to properly include injection as part of choice text.
Looking into this now.

**Comment by real-ezTheDev** [comment]
the fix should be in main now. Feel free to re-open if still occurs.
