### ISSUE TITLE
Im at the tutorial timestamp 9:39 and Godot Engine just hangs. Does not respond to exit, I must use task manager to kill Godot.

### ISSUE THREAD

**Issue by troynall** [real-ezTheDev/GodotEzDialoguePlugin#16]
Im using v4.2.1.stable.mono.official [b09f793f5]
Im am following you tutorial to the letter. Im at timestamp 9:39 and my Godot Engine/Editor Locks up.
Im at the point in the tutorial where we are creating the ChoiceButton functions.
I try to close engine down AND try to "reload" current project...But godot engine just hangs.
I have to pull up task manager and cancel task.

How I do a "dump" to help you figure this out ?

**Comment by troynall** [comment]
Tried to create a sump file from task manager but the file was 1460 MB and only 25MB is the upload filesize for github.

**Comment by real-ezTheDev** [comment]
oh oops, sorry i was not notified about this issue! i'll take a look and help fix!

**Comment by real-ezTheDev** [comment]
@troynall  if you still need help with this I can take a look!
Could you upload your project as repository for me to look at or you can join our discord and I can help you directly and more rapidly that way.

**Comment by real-ezTheDev** [comment]
closing the issue due to inactivity. feel free to open again if still facing this issue.
