### ISSUE TITLE
State only allows for non nested dictionary variables

### ISSUE THREAD

**Issue by SeanKR-IRE** [real-ezTheDev/GodotEzDialoguePlugin#18]
when trying to pass in a state that has a dictionary (possibly array didn't check) it only registeres the first key and ignores the rest. 
for example trying to pass in a dictionary of the players stats and trying to access their charisma it wont register

$if playerStats["Charisma"] >= 40{ ...
or direct access like
${playerStats["Charisma"]} 
results in <null> passed into the text. 
Be nice for this to be implemented, some form of recursion if _stateReference value is a dictionary or array since it's stored as one in memory. 

Edit: Signals could be revamped to allow for parameters but this can be done by the user in their own code.

**Comment by real-ezTheDev** [comment]
the updated fix is in dev branch now!
Please replace the addon with the dev version and see if your project still works.
After you confirm, I'll push the changes to main.

**Comment by SeanKR-IRE** [comment]
Sorry I'm not greate when it comes to github issues commenting, Found an issue and possible fix:
https://github.com/real-ezTheDev/GodotEzDialoguePlugin/commit/a7139fcd9e5180c4c1a7ec0a2ac280d3a1af2801#r144784195

**Comment by real-ezTheDev** [comment]
added a response to the comment https://github.com/real-ezTheDev/GodotEzDialoguePlugin/commit/a7139fcd9e5180c4c1a7ec0a2ac280d3a1af2801#r144784635

do you mean you want the "null" value to be replaced as "" instead of "<null>" which it is doing right now.

**Comment by real-ezTheDev** [comment]
in any case, 
this commit (most recent dev) makes it so that "null" value is replaced as empty string
https://github.com/real-ezTheDev/GodotEzDialoguePlugin/commit/8e74b9e5e10a823e9b4de7b3d520794664d23698

please verify fix!

**Comment by real-ezTheDev** [comment]
btw I reviewed and worked on this feature live today!
Here's the recorded session https://youtube.com/live/0BRjXEzmphc?feature=share

**Comment by SeanKR-IRE** [comment]
Not really, the issue stems from it overwriting anything in the expression since value in the else is determined by _stateReference, if _stateReference is null that should indicate 2 possible things i feel,
1. the value is a conditional check like "true" or a string comparison that's not actually a _stateReference
2. the user maybe entered the expression wrong in the dialogue node. This might be showcased to the user as a printerr but that would be more annoying if the intended outcome was 1.
example of what i meant for line 180, just placing if value: before if not value is String: and encasing everything inside.
```
	for variable in requiredVariables:
		var value = "" 
		if variable is Array:
			value = _recursion_search_inject(_stateReference,variable,1)
			if not value is String:
				value = str(value)
			workingExpression = workingExpression.replace(
				variable[0], value)
		else:
			value = _stateReference.get(variable)
			if value:
				if not value is String:
					value = str(value)
				workingExpression = workingExpression.replace(
					variable, value)
```
if value isn't checked it'll overwrite anything not in the _stateReference with null 
```
_stateRef = {"stored":{
                        "value":4,
                        },
                    }
                    
expression : stored["value"] == 4
```
the first pass would make workingExpression 
4 == 4
but since there's no 4 in _stateReference on the second pass it'll actually change it to 
<null> == <null> since you're replacing every instance of 4 in this case with null. might be okay for 1 conditonal expression but if it became something like
stored["value"] != 4 || stored["value"] ==6
that'll now become <null> != <null> || <null> == <null> 

Sorry for the long explenation 😅 hopefully I was okay at explaining

**Comment by real-ezTheDev** [comment]
Ah I see the confusion for me. I was talking about the case for variable injection in string case.

Right, I also remember having test cases for null value, and undefined variable evaluation result. I'll add tests and fixes for nested expression evaluation for conditional and fix! Thanks for the comment!

**Comment by SeanKR-IRE** [comment]
I'm so sorry! I meant to put that comment on in between these lines https://github.com/real-ezTheDev/GodotEzDialoguePlugin/blob/8e74b9e5e10a823e9b4de7b3d520794664d23698/addons/ez_dialogue/dialogue_reader.gd#L230-L231

That's 100% my fault for causing the confusion
The issue was with _evaluate_conditional_expression

**Comment by real-ezTheDev** [comment]
Here's last night's live working on it https://www.youtube.com/live/Ac3i_S6iCb4?si=obQbnfVVxkn15_8o

**Comment by real-ezTheDev** [comment]
merged your changes! and i'll be doing some testing.
I noticed you had some QoL request for printerr in regards to including the error messaging.
Do you  mind creating a separate issue with more clarification on it?

I think I have an idea for it, but just wanted to make sure i understand how you wanted it to present itself!
I'm closing this issue for now!

**Comment by real-ezTheDev** [comment]
nvm I added the "current node name" in the print err as requested in the most recent dev commit: 68450ed49911a1230d1d5b156a109bee2130c984
