### ISSUE TITLE
[Bug/Feature] Multiple deadend player choices

### ISSUE THREAD

**Issue by SeanKR-IRE** [real-ezTheDev/GodotEzDialoguePlugin#24]
Be default you can't have multiple dead end choice operatiors. It can be midigated by a GOTO to an empty dialogue node but that can be messy in the editor graph. Don't know if intentional or a bug. 

Reason for feature: Be nice for illusion of choice, while somewhat frowned appon it could give the player a feeling of doing something even if it leads no where either way.

Current:
![image](https://github.com/user-attachments/assets/3bfa865b-4167-4df7-aebb-056dcdd89782)

How it should be (excluding the -> 
![image](https://github.com/user-attachments/assets/136c3a39-4e5d-4061-bc05-a9813637756b)

**Comment by real-ezTheDev** [comment]
another way to work around is to have empty bracketing for the choice like this
![image](https://github.com/user-attachments/assets/c677872a-8813-4cf7-a1cd-8c59a00f91e6)

Thinking about it... I'm not 100% sure if we should quietly accept dead end choices with. I feel like it should require some "effort" to make something a "nothing" choice like the brackets. What do you think? 

At the least we can document it.

for now I made a change to include the test for "dead end" choices.
3b39d01ad8b93a4064f220d57cc934de3c7f02bc

**Comment by real-ezTheDev** [comment]
documentation added and closing the issue for now!
06314dcd13f63b5eb7768e0ead03baa464e21b59
