### ISSUE TITLE
When changing name/removing already "connected" nodes, error messaging fills the log

### ISSUE THREAD

**Issue by real-ezTheDev** [real-ezTheDev/GodotEzDialoguePlugin#3]
This has no actual impact on the functionality, but the extra error lines printed on log every time I updated an already connected dialogue node is annoying.

**Comment by adrientremblay** [comment]
I get this too. It triggeres without me necessarily doing something. Possible has something to do with the current state of my dialogue.json.
![image](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/8109538/6f27bc2d-cd41-40da-9169-4fce58fc02ba)

**Comment by adrientremblay** [comment]
![image](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/8109538/cac0d7a6-d025-412e-a6fb-bbd8202b0a50)

**Comment by adrientremblay** [comment]
I created an issue on the Godot repo. Apparently the issue has already been fixed and will be out in an upcoming 4.2 release

**Comment by real-ezTheDev** [comment]
hey @adrientremblay thanks for working on this. 
It may take me a second to figure out your merge request haha..
I'll get back to this issue and your merge request soon.

**Comment by real-ezTheDev** [comment]
it does appear, the issue with log error when changing connected node name is fixed.
However, the "deletion" still triggers it. 
I believe it is because there are other parts of the code that still uses "to" as well instead of "to_node"
will correct.

**Comment by real-ezTheDev** [comment]
Found that manually "disconnecting" connection when also "queue_free" on the graph nodes would result in "node not found" error. Making changes to skip the manual "disconnection" of nodes when "deleting" a node.

**Comment by real-ezTheDev** [comment]
verified issues are fixed in dev branch. Will go out to main branch in the next major update.
