### ISSUE TITLE
Choice options stay after being selected

### ISSUE THREAD

**Issue by ZapPlays** [real-ezTheDev/GodotEzDialoguePlugin#6]
From what I can tell, my code is exactly the same as the one presented in the tutorial, yet the choice buttons persist after already being selected. I'm still new to Godot and coding in general, so I'm unsure how to go about solving this. Any and all help would be greatly appreciated.

![Screenshot (65)](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/149829408/cdb04bfc-f7ce-4de5-af3c-7511637b3fd2)
![Screenshot (66)](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/149829408/9d2d6cd0-adaa-4aef-b5e3-3a0769da64b9)
![Screenshot (67)](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/149829408/439ea9a2-fd89-4801-97dd-dd5f3511c0aa)
![Screenshot (68)](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/149829408/11613351-3156-45d2-9ea7-175784e628a2)
![Screenshot (69)](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/149829408/5253fb77-d211-49a6-bad8-461574db7a41)
![Screenshot (70)](https://github.com/real-ezTheDev/GodotEzDialoguePlugin/assets/149829408/ecd800b2-b7ae-4b16-92c3-9cd2aa2618ae)

**Comment by ZapPlays** [comment]
Just to make sure, I started a new project with just the EzDialogue addon and was still recieving the same results.

**Comment by real-ezTheDev** [comment]
So sorry it's taking me long to look.
I just am not around my computer throughput this trip, so it is taking me a while.
I'll be able to take a look in next 2 days!

**Comment by ZapPlays** [comment]
All good. No rush 👍

**Comment by real-ezTheDev** [comment]
hey!
So in your DialogueBox.gd function called "clear_dialogue_box"
you have a line that says:
$VBoxContainer/Text.remove_child(choice)

1. it should actully be $VBoxContainer.remove_child(choice) instead of "$VBoxContainer/Text"
2. Actually there should be additional line which i forgot so in total you should have something like.

```
$VBoxContainer.remove_child(choice)
choice.queue_free()
```

**Comment by ZapPlays** [comment]
> hey! So in your DialogueBox.gd function called "clear_dialogue_box" you have a line that says: $VBoxContainer/Text.remove_child(choice)
> 
> 1. it should actully be $VBoxContainer.remove_child(choice) instead of "$VBoxContainer/Text"
> 2. Actually there should be additional line which i forgot so in total you should have something like.
> 
> ```
> $VBoxContainer.remove_child(choice)
> choice.queue_free()
> ```

YEP! That worked! Simple coding mistake on my part. Thanks for the help, I really appreciate it.
